export const CONFIG = {
  recipient: process.env.ALERT_EMAIL_TO || "sheng.chi@qq.com",
  from: process.env.ALERT_EMAIL_FROM || "Signal Alerts <alerts@example.com>",
  cryptoAssets: [
    "BTCUSDT",
    "ETHUSDT",
    "BNBUSDT",
    "SOLUSDT",
    "XRPUSDT",
    "DOGEUSDT",
    "ADAUSDT",
    "AVAXUSDT",
    "LINKUSDT",
    "LTCUSDT",
    "DOTUSDT",
    "TRXUSDT",
    "BCHUSDT",
    "NEARUSDT",
    "APTUSDT",
    "ARBUSDT",
    "OPUSDT",
    "SUIUSDT",
    "INJUSDT",
    "UNIUSDT",
    "FILUSDT",
    "ATOMUSDT",
    "ETCUSDT",
    "AAVEUSDT"
  ],
  futuresAssets: [
    "BTCUSDT",
    "ETHUSDT",
    "BNBUSDT",
    "SOLUSDT",
    "XRPUSDT",
    "DOGEUSDT",
    "ADAUSDT",
    "AVAXUSDT",
    "LINKUSDT",
    "LTCUSDT",
    "BCHUSDT",
    "TRXUSDT",
    "SUIUSDT",
    "INJUSDT"
  ],
  futuresArbitrageAssets: [
    "BTCUSDT",
    "ETHUSDT",
    "BNBUSDT",
    "SOLUSDT",
    "XRPUSDT",
    "DOGEUSDT",
    "ADAUSDT",
    "AVAXUSDT",
    "LINKUSDT",
    "LTCUSDT"
  ],
  scanGroups: {
    "crypto-core": ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "LINKUSDT", "LTCUSDT"],
    "crypto-core-a": ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT"],
    "crypto-core-b": ["DOGEUSDT", "ADAUSDT", "AVAXUSDT", "LINKUSDT", "LTCUSDT"],
    "crypto-alt": ["DOTUSDT", "TRXUSDT", "BCHUSDT", "NEARUSDT", "APTUSDT", "ARBUSDT", "OPUSDT", "SUIUSDT", "INJUSDT", "UNIUSDT", "FILUSDT", "ATOMUSDT", "ETCUSDT", "AAVEUSDT"],
    "crypto-alt-a": ["DOTUSDT", "TRXUSDT", "BCHUSDT", "NEARUSDT", "APTUSDT"],
    "crypto-alt-b": ["ARBUSDT", "OPUSDT", "SUIUSDT", "INJUSDT", "UNIUSDT"],
    "crypto-alt-c": ["FILUSDT", "ATOMUSDT", "ETCUSDT", "AAVEUSDT"],
    "futures-core": ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "LINKUSDT", "LTCUSDT", "BCHUSDT", "TRXUSDT", "SUIUSDT", "INJUSDT"],
    "futures-scalp-a": ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT"],
    "futures-scalp-b": ["AVAXUSDT", "LINKUSDT", "LTCUSDT", "BCHUSDT", "TRXUSDT", "SUIUSDT", "INJUSDT"],
    "futures-arbitrage": ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "LINKUSDT", "LTCUSDT"]
  },
  intervals: ["4h", "1d"],
  shortTermIntervals: ["1h", "2h"],
  futuresScalpIntervals: ["15m", "30m"],
  minTrades: 40,
  futuresScalpMinTrades: 35,
  futuresScalpMinRecommendationScore: Number(process.env.FUTURES_SCALP_MIN_RECOMMENDATION_SCORE || 72),
  futuresScalpObservationMinRecommendationScore: Number(process.env.FUTURES_SCALP_OBSERVATION_MIN_RECOMMENDATION_SCORE || 62),
  futuresScalpMinRecentWinRate: Number(process.env.FUTURES_SCALP_MIN_RECENT_WIN_RATE || 0.48),
  futuresScalpMinAverageReturn: Number(process.env.FUTURES_SCALP_MIN_AVERAGE_RETURN || 0.0015),
  recentWindowBars: 240,
  minRecentTradesForPenalty: 5,
  minRecentWinRateForStrongSignal: 0.45,
  minRecentReturnForStrongSignal: -0.03,
  minLiveTradesForPenalty: 3,
  livePerformanceLookback: 80,
  maxAlertReviewsPerRun: Number(process.env.MAX_ALERT_REVIEWS_PER_RUN || 12),
  livePerformanceMinWinRate: 0.45,
  livePerformanceMinReturn: -0.04,
  cryptoLongRequiresBenchmarkTrend: true,
  relativeStrengthOverride: true,
  relativeStrengthMinMomentum24h: 0.08,
  relativeStrengthMinVolumeMultiple: 1.5,
  relativeStrengthScorePenalty: -4,
  assetSignalCooldownHours: 24,
  dynamicSpotPoolEnabled: true,
  dynamicSpotPoolMaxAssets: 8,
  dynamicSpotPoolMinQuoteVolume: 3000000,
  dynamicSpotPoolMinPriceChangePercent: 5,
  dynamicSpotPoolExcludedPatterns: ["UPUSDT", "DOWNUSDT", "BULLUSDT", "BEARUSDT"],
  marketDataConcurrency: Number(process.env.MARKET_DATA_CONCURRENCY || 3),
  batchGroupConcurrency: Number(process.env.BATCH_GROUP_CONCURRENCY || 2),
  minRecommendationScore: 65,
  observationMinRecommendationScore: Number(process.env.OBSERVATION_MIN_RECOMMENDATION_SCORE || 58),
  riskAlertMinRecommendationScore: Number(process.env.RISK_ALERT_MIN_RECOMMENDATION_SCORE || 55),
  maxSignalsPerEmail: 5,
  maxSignalCurrentPriceDriftPct: Number(process.env.MAX_SIGNAL_CURRENT_PRICE_DRIFT_PCT || 0.02),
  cryptoTradingCost: 0.002,
  futuresTradingCost: 0.0012,
  futuresStopAtrMultiplier: Number(process.env.FUTURES_STOP_ATR_MULTIPLIER || 1.6),
  futuresRewardRiskRatio: Number(process.env.FUTURES_REWARD_RISK_RATIO || 1.8),
  futuresMaxSuggestedLeverage: Number(process.env.FUTURES_MAX_SUGGESTED_LEVERAGE || 3),
  futuresMaxPositionRiskPct: Number(process.env.FUTURES_MAX_POSITION_RISK_PCT || 0.01),
  futuresMaxLeveragedStopPct: Number(process.env.FUTURES_MAX_LEVERAGED_STOP_PCT || 0.12),
  arbitrageTradingCost: 0.0028,
  arbitrageAnnualizedThreshold: Number(process.env.ARBITRAGE_ANNUALIZED_THRESHOLD || 0.30),
  arbitrageFundingRateThreshold: 0.0003,
  arbitrageWatchFundingRateThreshold: 0.0002,
  arbitrageMaxBreakEvenDays: 5,
  arbitrageStrongMaxBreakEvenDays: 3,
  arbitrageMinNetDailyAfterCost: 0.0002
};

export function intervalHours(interval) {
  const map = {
    "15m": 0.25,
    "30m": 0.5,
    "1h": 1,
    "2h": 2,
    "4h": 4,
    "1d": 24
  };
  return map[interval] || 24;
}
