export const CONFIG = {
  recipient: process.env.ALERT_EMAIL_TO || "sheng.chi@qq.com",
  from: process.env.ALERT_EMAIL_FROM || "Signal Alerts <alerts@example.com>",
  cryptoAssets: [
    "BTCUSDT",
    "ETHUSDT",
    "BNBUSDT",
    "SOLUSDT",
    "XRPUSDT",
    "DOGEUSDT",
    "ADAUSDT",
    "AVAXUSDT",
    "LINKUSDT",
    "LTCUSDT",
    "DOTUSDT",
    "TRXUSDT",
    "BCHUSDT",
    "NEARUSDT",
    "APTUSDT",
    "ARBUSDT",
    "OPUSDT",
    "SUIUSDT",
    "INJUSDT",
    "UNIUSDT",
    "FILUSDT",
    "ATOMUSDT",
    "ETCUSDT",
    "AAVEUSDT"
  ],
  futuresAssets: [
    "BTCUSDT",
    "ETHUSDT",
    "BNBUSDT",
    "SOLUSDT",
    "XRPUSDT",
    "DOGEUSDT",
    "ADAUSDT",
    "AVAXUSDT",
    "LINKUSDT",
    "LTCUSDT",
    "BCHUSDT",
    "TRXUSDT",
    "SUIUSDT",
    "INJUSDT"
  ],
  futuresArbitrageAssets: [
    "BTCUSDT",
    "ETHUSDT",
    "BNBUSDT",
    "SOLUSDT",
    "XRPUSDT",
    "DOGEUSDT",
    "ADAUSDT",
    "AVAXUSDT",
    "LINKUSDT",
    "LTCUSDT"
  ],
  equityAssets: ["SPY", "QQQ", "DIA", "IWM", "AAPL", "MSFT", "NVDA", "AMZN", "GOOGL", "META", "TSLA"],
  commodityAssets: ["USO", "GLD", "SLV"],
  scanGroups: {
    "crypto-core": ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "LINKUSDT", "LTCUSDT"],
    "crypto-core-a": ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT"],
    "crypto-core-b": ["DOGEUSDT", "ADAUSDT", "AVAXUSDT", "LINKUSDT", "LTCUSDT"],
    "crypto-alt": ["DOTUSDT", "TRXUSDT", "BCHUSDT", "NEARUSDT", "APTUSDT", "ARBUSDT", "OPUSDT", "SUIUSDT", "INJUSDT", "UNIUSDT", "FILUSDT", "ATOMUSDT", "ETCUSDT", "AAVEUSDT"],
    "crypto-alt-a": ["DOTUSDT", "TRXUSDT", "BCHUSDT", "NEARUSDT", "APTUSDT"],
    "crypto-alt-b": ["ARBUSDT", "OPUSDT", "SUIUSDT", "INJUSDT", "UNIUSDT"],
    "crypto-alt-c": ["FILUSDT", "ATOMUSDT", "ETCUSDT", "AAVEUSDT"],
    "futures-core": ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "LINKUSDT", "LTCUSDT", "BCHUSDT", "TRXUSDT", "SUIUSDT", "INJUSDT"],
    "futures-arbitrage": ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "LINKUSDT", "LTCUSDT"],
    "tradfi": ["SPY", "QQQ", "DIA", "IWM", "AAPL", "MSFT", "NVDA", "AMZN", "GOOGL", "META", "TSLA", "USO", "GLD", "SLV"]
  },
  intervals: ["4h", "1d"],
  shortTermIntervals: ["1h", "2h"],
  minTrades: 40,
  recentWindowBars: 240,
  minRecentTradesForPenalty: 5,
  minRecentWinRateForStrongSignal: 0.45,
  minRecentReturnForStrongSignal: -0.03,
  minLiveTradesForPenalty: 3,
  livePerformanceLookback: 80,
  livePerformanceMinWinRate: 0.45,
  livePerformanceMinReturn: -0.04,
  cryptoLongRequiresBenchmarkTrend: true,
  relativeStrengthOverride: true,
  relativeStrengthMinMomentum24h: 0.08,
  relativeStrengthMinVolumeMultiple: 1.5,
  relativeStrengthScorePenalty: -4,
  assetSignalCooldownHours: 24,
  dynamicSpotPoolEnabled: true,
  dynamicSpotPoolMaxAssets: 8,
  dynamicSpotPoolMinQuoteVolume: 3000000,
  dynamicSpotPoolMinPriceChangePercent: 5,
  dynamicSpotPoolExcludedPatterns: ["UPUSDT", "DOWNUSDT", "BULLUSDT", "BEARUSDT"],
  marketDataConcurrency: Number(process.env.MARKET_DATA_CONCURRENCY || 3),
  minRecommendationScore: 65,
  maxSignalsPerEmail: 5,
  cryptoTradingCost: 0.002,
  futuresTradingCost: 0.0012,
  arbitrageTradingCost: 0.0028,
  arbitrageAnnualizedThreshold: Number(process.env.ARBITRAGE_ANNUALIZED_THRESHOLD || 0.30),
  arbitrageFundingRateThreshold: 0.0003,
  arbitrageWatchFundingRateThreshold: 0.0002,
  arbitrageMaxBreakEvenDays: 5,
  arbitrageStrongMaxBreakEvenDays: 3,
  arbitrageMinNetDailyAfterCost: 0.0002,
  equityTradingCost: 0.001
};

export function intervalHours(interval) {
  const map = {
    "1h": 1,
    "2h": 2,
    "4h": 4,
    "1d": 24
  };
  return map[interval] || 24;
}
